network:
  ethernets:
    enp1s0:
      addresses:
      - 192.168.122.10/24
      nameservers:
        addresses:
        - 192.168.122.1
        search: []
      routes:
      - to: default
        via: 192.168.122.1
  version: 2

