---
- hosts: "{{ host }}"
  become: true
  gather_facts: no
  tasks:
  - copy:
      src: cka/
      dest: /home/k8s/cka/
      force: yes
  - name: set hostname
    hostname:
      name: "{{ hostname }}"
  - name: setup CRI
    command: /home/steve/cka/setup-container.sh
    ignore_errors: true
  - name: setup KUBETOOLS
    command: /home/steve/cka/setup-kubetools.sh
    ignore_errors: true
