---
- hosts: "{{ host }}"
  become: true
  gather_facts: no
  tasks:
  - name: set hostname
    hostname:
      name: "{{ hostname }}"
  - name: Configure netplan
    template:
      src: netplan.j2
      dest: /etc/netplan/00-installer-config.yaml
      mode: 0400
    vars:
      interface_name: "enp1s0"
      ip: "{{ ip_addr }}"
      gateway: 192.168.122.1
      dns: 192.168.122.1
  - name: Apply netplan configuration
    command:
      cmd: netplan apply

